version: "3.9"

services:
  web:
    build: .
    container_name: chat_api
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: chat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  postgres_data:
