"""fix relationship in the Chat model

Revision ID: 4414d544186c
Revises: f72102e44f0c
Create Date: 2023-05-19 18:43:26.253105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4414d544186c'
down_revision = 'f72102e44f0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
