"""add name field to Chat model

Revision ID: 54cb16d37053
Revises: 4b906b1d974d
Create Date: 2023-05-19 18:10:48.603070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54cb16d37053'
down_revision = '4b906b1d974d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'name')
    # ### end Alembic commands ###
