"""add relationships to the models

Revision ID: d24722488d12
Revises: fd8415ccda78
Create Date: 2023-05-19 18:37:40.924294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24722488d12'
down_revision = 'fd8415ccda78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_owner_fkey', 'chat', type_='foreignkey')
    op.drop_column('chat', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chat_owner_fkey', 'chat', 'user', ['owner'], ['id'])
    # ### end Alembic commands ###
