"""fix relationship in the Chat model

Revision ID: f72102e44f0c
Revises: d24722488d12
Create Date: 2023-05-19 18:42:16.701580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72102e44f0c'
down_revision = 'd24722488d12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_column('chat', 'owner_id')
    # ### end Alembic commands ###
