"""fix typo in created at field

Revision ID: fd8415ccda78
Revises: 54cb16d37053
Create Date: 2023-05-19 18:15:27.142973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd8415ccda78'
down_revision = '54cb16d37053'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('chat', 'created_ad')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('created_ad', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('chat', 'created_at')
    # ### end Alembic commands ###
